new_dataset:
  best_features_names_out_folder: results/best_indices_filtered_final/
  out_folder: best_features_dataset
  dataclass_in_folder: best_features_dataset/dataclass
  dataset_text_file: best_features_dataset/best_97_dataset.txt

full_dataset:
  dataclass_in_folder: /media/athishramdas/data/Pangenome-archive/tf_records_dataclass

supporting_files:
  fi_folder: /home/athishramdas/Desktop/Pangenome/pangenome-project/explanations
  serotype_file_path: /home/athishramdas/Desktop/Pangenome/pangenome-project/data/SRA_Serotype_file.csv
  

corr_matrix:
  out_file: results/correlation_matrix/corr_matrix.csv
  filtered_indices_file: results/correlation_matrix/filtered_indices.txt