pgg:
  logfile: ./logs/pgg.log
  sequence_map_pickle_path: ./cache/sequence_map.pkl
  pgg_file: ./MosesFiles/pggb_100_original.gfa

xai:
  train_data_cache_path: ./cache/dataloader_cache/train_loader.pkl
  val_data_cache_path: ./cache/dataloader_cache/valid_loader.pkl
  test_data_cache_path: ./cache/dataloader_cache/test_loader.pkl
  
prepare_dataset:
  serotype_mapping_file: ./cache/dataclass/metadata/serotype_mapping.txt
  serotype_mapping_pickle: ./cache/dataclass/metadata/serotype_mapping.pkl
  dataclass_out_folder_full: /media/athishramdas/data/Pangenome-archive/dataclass_dataset/full
