primer_info:
  fin150_30_3: ./data/GoodPosForPrimer/fin150_30_3.pkl 
  fin150_40_3: ./data/GoodPosForPrimer/fin150_40_3.pkl
  fin150_50_3: ./data/GoodPosForPrimer/fin150_50_3.pkl
  fin500_30_3: ./data/GoodPosForPrimer/fin500_30_3.pkl
  fin500_40_3: ./data/GoodPosForPrimer/fin500_40_3.pkl
  fin500_50_3: ./data/GoodPosForPrimer/fin500_50_3.pkl

hyperparams:
  top_n: 100
  out_dir: primer_sites 
