dataset:
  dataset_used: full
  zip_path: ./data/tfrecord_to_sample
  serotype_file_path: ./data/SRA_Serotype_file.csv
  input_size: 236071 #236068
  lowest_index: 0
  num_classes: 2054
  sparse_vals_used: False
  test_size: 0.2
  val_size: 0.1
  random_state: 42
