defaults:
  - base
  
dataset:
  zip_path: ../data/tfrecord_to_sample
  serotype_file_path: ../data/SRA_Serotype_file.csv
  partial_used: True
  num_classes: 10 # Should match the number of classes listed in 'classes'
  classes:
    - Enteritidis
    - Typhimurium
    - Newport
    - Infantis
    - I14512i-
    - Typhi
    - Javiana
    - Kentucky
    - Montevideo
    - Saintpaul
