defaults:
  - base
  
dataset:
  zip_path: /home/ShareDirectory/Adam_Project/TF_Extracted/TFRecord_to_sample
  serotype_file_path: /home/ShareDirectory/Adam_Project/TF_Extracted/SRA_Serotype_file.csv
