dataset:
  out_folder: best_features_dataset
  dataclass_out_folder: best_features_dataclass
  best_features_in_file: /home/athishramdas/Desktop/Pangenome/pangenome-project/results/best_indices_filtered/RF_Important_Indices.txt
  
windowed:
  selected_windows_file: input_data/best_contigs_windows/best_contigs_windows_150.txt
  out_folder: /home/athishramdas/Desktop/Pangenome/transformer-attempt/pangenome-project/windowed_dataset
  window_size: 34
  num_windows: 67